export enum genres {
  Fiction = 'Fiction',
  NonFiction = 'Non-fiction',
  Mystery = 'Mystery',
  Fantasy = 'Fantasy',
  ScienceFiction = 'Science Fiction',
  Biography = 'Biography',
  Romance = 'Romance',
  Thriller = 'Thriller',
  Historical = 'Historical',
  Horror = 'Horror',
  SelfHelp = 'Self-Help',
  Poetry = 'Poetry',
  GraphicNovel = 'Graphic Novel',
  YoungAdult = 'Young Adult',
  Children = "Children's",
}
